### ISSUE TITLE
Important

### ISSUE THREAD

**Issue by zainaftab44** [MoujTechnologies/Company-Stationary#1]
kia chussain marni ha yahan py ye to bta dy.........
kn sa material ae v das dy???

**Comment by mutafaf** [comment]
O any material that we'll be sharing.. Bhai tu ny Hi organnization bnai.. I started via sharing logo PSD & PNG, ager kisi ko zaroorat ho to yahan sy ly skta.. Ahsan yahan abi cover ki PSD PNG share kry ga ..

**Comment by zainaftab44** [comment]
ok
